# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Import applicants_data.csv to Google Colab
from google.colab import files
uploaded = files.upload()

Saving applicants_data.csv to applicants_data.csv

In [26]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv("applicants_data.csv")

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [27]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [28]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN','NAME'])

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [29]:
applicant_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [30]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == 'object'].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [ ]:
# Imports
from sklearn.preprocessing import OneHotEncoder

In [31]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [32]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [33]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data, columns=enc.get_feature_names(categorical_variables))

# Review the DataFrame
encoded_df.head()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [35]:
# Create a DataFrame with the columnns containing numerical variables from the original dataset
numerical_variables_df = applicant_data_df.drop(columns=categorical_variables)

# Review the DataFrame
numerical_variables_df.head()

   STATUS  ASK_AMT  IS_SUCCESSFUL
0       1     5000              1
1       1   108590              1
2       1     5000              0
3       1     6692              1
4       1   142590              1

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [36]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([numerical_variables_df,encoded_df], axis=1)

# Review the DataFrame
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [37]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [38]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=['IS_SUCCESSFUL'])

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [39]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [40]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [41]:
X_train.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
10679,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5052,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9990,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
25173,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11405,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [80]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [81]:
# Define the number of neurons in the output layer
number_output_neurons = (number_input_features +1) //2

In [82]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  number_output_neurons

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [83]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 +1) //2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [84]:
# Create the Sequential model instance
nn = Sequential()

In [85]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1,input_dim=number_input_features, activation='relu'))

In [86]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2,activation='relu'))

In [87]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation='sigmoid'))

In [88]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_8 (Dense)             (None, 58)                6786

 dense_9 (Dense)             (None, 29)                1711

 dense_10 (Dense)            (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [89]:
# Compile the Sequential model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [90]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5762 - accuracy: 0.7173
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5536 - accuracy: 0.7292
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5498 - accuracy: 0.7304
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5484 - accuracy: 0.7308
Epoch 5/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5470 - accuracy: 0.7325
Epoch 6/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5451 - accuracy: 0.7337
Epoch 7/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5440 - accuracy: 0.7319
Epoch 8/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5439 - accuracy: 0.7336
Epoch 9/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5429 - accuracy: 0.7347
Epoch 10/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5431 - accuracy: 0.7334
Epoch 11/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5418 - accuracy: 0.7358
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5415 - accuracy: 0.7344
Epoch 13/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5411 - accuracy: 0.7350
Epoch 14/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5407 - accuracy: 0.7350
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5401 - accuracy: 0.7358
Epoch 16/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5395 - accuracy: 0.7362
Epoch 17/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5394 - accuracy: 0.7373
Epoch 18/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5390 - accuracy: 0.7365
Epoch 19/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5386 - accuracy: 0.7366
Epoch 20/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5380 - accuracy: 0.7381
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5382 - accuracy: 0.7372
Epoch 22/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5372 - accuracy: 0.7386
Epoch 23/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5371 - accuracy: 0.7381
Epoch 24/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5369 - accuracy: 0.7376
Epoch 25/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7387
Epoch 26/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5366 - accuracy: 0.7378
Epoch 27/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5360 - accuracy: 0.7395
Epoch 28/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5360 - accuracy: 0.7393
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5355 - accuracy: 0.7380
Epoch 30/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5353 - accuracy: 0.7400
Epoch 31/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.7392
Epoch 32/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5349 - accuracy: 0.7391
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5350 - accuracy: 0.7394
Epoch 34/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7393
Epoch 35/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5347 - accuracy: 0.7401
Epoch 36/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5341 - accuracy: 0.7399
Epoch 37/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5343 - accuracy: 0.7403
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5341 - accuracy: 0.7413
Epoch 39/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5342 - accuracy: 0.7400
Epoch 40/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5338 - accuracy: 0.7394
Epoch 41/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5336 - accuracy: 0.7399
Epoch 42/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5336 - accuracy: 0.7398
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5331 - accuracy: 0.7400
Epoch 44/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5329 - accuracy: 0.7412
Epoch 45/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5329 - accuracy: 0.7402
Epoch 46/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5328 - accuracy: 0.7396
Epoch 47/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5328 - accuracy: 0.7402
Epoch 48/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5327 - accuracy: 0.7411
Epoch 49/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.7409
Epoch 50/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5321 - accuracy: 0.7407
Epoch 51/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5320 - accuracy: 0.7418
Epoch 52/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5321 - accuracy: 0.7411
Epoch 53/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5318 - accuracy: 0.7414
Epoch 54/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5317 - accuracy: 0.7404
Epoch 55/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5313 - accuracy: 0.7410
Epoch 56/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5313 - accuracy: 0.7412
Epoch 57/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5313 - accuracy: 0.7419
Epoch 58/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5311 - accuracy: 0.7413
Epoch 59/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5311 - accuracy: 0.7416
Epoch 60/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5310 - accuracy: 0.7405
Epoch 61/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5310 - accuracy: 0.7408
Epoch 62/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5310 - accuracy: 0.7416
Epoch 63/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5310 - accuracy: 0.7410
Epoch 64/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5307 - accuracy: 0.7420
Epoch 65/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5307 - accuracy: 0.7404
Epoch 66/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5307 - accuracy: 0.7414
Epoch 67/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5307 - accuracy: 0.7405
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.7421
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.7413
Epoch 70/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.7418
Epoch 71/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5300 - accuracy: 0.7419
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5299 - accuracy: 0.7411
Epoch 73/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5301 - accuracy: 0.7422
Epoch 74/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5301 - accuracy: 0.7417
Epoch 75/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5298 - accuracy: 0.7417
Epoch 76/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5297 - accuracy: 0.7418
Epoch 77/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5296 - accuracy: 0.7411
Epoch 78/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5296 - accuracy: 0.7424
Epoch 79/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5297 - accuracy: 0.7416
Epoch 80/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5293 - accuracy: 0.7415
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5295 - accuracy: 0.7424
Epoch 82/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5292 - accuracy: 0.7418
Epoch 83/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5294 - accuracy: 0.7414
Epoch 84/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5295 - accuracy: 0.7416
Epoch 85/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5292 - accuracy: 0.7423
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5290 - accuracy: 0.7419
Epoch 87/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5292 - accuracy: 0.7424
Epoch 88/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5286 - accuracy: 0.7424
Epoch 89/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5292 - accuracy: 0.7416
Epoch 90/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5287 - accuracy: 0.7415
Epoch 91/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5287 - accuracy: 0.7417
Epoch 92/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5289 - accuracy: 0.7421
Epoch 93/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5285 - accuracy: 0.7414
Epoch 94/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5283 - accuracy: 0.7418
Epoch 95/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5286 - accuracy: 0.7427
Epoch 96/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5285 - accuracy: 0.7416
Epoch 97/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5287 - accuracy: 0.7412
Epoch 98/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5286 - accuracy: 0.7420
Epoch 99/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5284 - accuracy: 0.7425
Epoch 100/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5283 - accuracy: 0.7429

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [91]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5649 - accuracy: 0.7307 - 754ms/epoch - 3ms/step
Loss: 0.5649033784866333, Accuracy: 0.7307288646697998

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [92]:
# Set the model's file path
file_path = "AlphabetSoup.h5"

# Export your model to a HDF5 file
nn.save(file_path)

# Download your model to your computer
files.download(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [116]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [117]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = (number_input_features + 1)//2

In [118]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = number_output_neurons_A1

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [119]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A1 = (hidden_nodes_layer1_A1 +1)//2

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A1

29

In [97]:
# Define the number of hidden nodes for the third hidden layer
hidden_nodes_layer3_A1 = (hidden_nodes_layer2_A1 +1)//2

# Review the number of hidden nodes in the second layer
hidden_nodes_layer3_A1

15

In [98]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [99]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation='relu'))

# Output layer
nn_A1.add(Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn_A1.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_11 (Dense)            (None, 58)                6786

 dense_12 (Dense)            (None, 1)                 59

=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

In [100]:
# Compile the Sequential model
nn_A1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [135]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=70)

Epoch 1/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5325 - accuracy: 0.7394
Epoch 2/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5319 - accuracy: 0.7426
Epoch 3/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5324 - accuracy: 0.7403
Epoch 4/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5324 - accuracy: 0.7403
Epoch 5/70
804/804 [==============================] - 4s 4ms/step - loss: 0.5325 - accuracy: 0.7400
Epoch 6/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5318 - accuracy: 0.7413
Epoch 7/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5327 - accuracy: 0.7399
Epoch 8/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5329 - accuracy: 0.7408
Epoch 9/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5325 - accuracy: 0.7404
Epoch 10/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5319 - accuracy: 0.7409
Epoch 11/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5325 - accuracy: 0.7405
Epoch 12/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5327 - accuracy: 0.7414
Epoch 13/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5322 - accuracy: 0.7406
Epoch 14/70
804/804 [==============================] - 4s 4ms/step - loss: 0.5326 - accuracy: 0.7414
Epoch 15/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5326 - accuracy: 0.7412
Epoch 16/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5320 - accuracy: 0.7395
Epoch 17/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.7406
Epoch 18/70
804/804 [==============================] - 4s 5ms/step - loss: 0.5321 - accuracy: 0.7405
Epoch 19/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5317 - accuracy: 0.7416
Epoch 20/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5320 - accuracy: 0.7413
Epoch 21/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5324 - accuracy: 0.7411
Epoch 22/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5407 - accuracy: 0.7399
Epoch 23/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5312 - accuracy: 0.7399
Epoch 24/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5320 - accuracy: 0.7414
Epoch 25/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5319 - accuracy: 0.7397
Epoch 26/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5310 - accuracy: 0.7405
Epoch 27/70
804/804 [==============================] - 4s 4ms/step - loss: 0.5318 - accuracy: 0.7413
Epoch 28/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5318 - accuracy: 0.7412
Epoch 29/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5316 - accuracy: 0.7418
Epoch 30/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5317 - accuracy: 0.7409
Epoch 31/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5314 - accuracy: 0.7406
Epoch 32/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5319 - accuracy: 0.7409
Epoch 33/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5321 - accuracy: 0.7420
Epoch 34/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5323 - accuracy: 0.7404
Epoch 35/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5314 - accuracy: 0.7405
Epoch 36/70
804/804 [==============================] - 4s 4ms/step - loss: 0.5317 - accuracy: 0.7415
Epoch 37/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5322 - accuracy: 0.7407
Epoch 38/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5320 - accuracy: 0.7408
Epoch 39/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5316 - accuracy: 0.7407
Epoch 40/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5316 - accuracy: 0.7405
Epoch 41/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.7402
Epoch 42/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5316 - accuracy: 0.7420
Epoch 43/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5319 - accuracy: 0.7413
Epoch 44/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5314 - accuracy: 0.7417
Epoch 45/70
804/804 [==============================] - 4s 5ms/step - loss: 0.5316 - accuracy: 0.7411
Epoch 46/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5336 - accuracy: 0.7417
Epoch 47/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5330 - accuracy: 0.7416
Epoch 48/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5313 - accuracy: 0.7415
Epoch 49/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5308 - accuracy: 0.7423
Epoch 50/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5315 - accuracy: 0.7407
Epoch 51/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5313 - accuracy: 0.7405
Epoch 52/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5315 - accuracy: 0.7412
Epoch 53/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5320 - accuracy: 0.7406
Epoch 54/70
804/804 [==============================] - 4s 5ms/step - loss: 0.5313 - accuracy: 0.7407
Epoch 55/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5313 - accuracy: 0.7404
Epoch 56/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5309 - accuracy: 0.7417
Epoch 57/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5320 - accuracy: 0.7412
Epoch 58/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5311 - accuracy: 0.7402
Epoch 59/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5317 - accuracy: 0.7409
Epoch 60/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5310 - accuracy: 0.7414
Epoch 61/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5315 - accuracy: 0.7410
Epoch 62/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5311 - accuracy: 0.7415
Epoch 63/70
804/804 [==============================] - 4s 5ms/step - loss: 0.5317 - accuracy: 0.7405
Epoch 64/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5311 - accuracy: 0.7420
Epoch 65/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5311 - accuracy: 0.7419
Epoch 66/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5310 - accuracy: 0.7407
Epoch 67/70
804/804 [==============================] - 4s 4ms/step - loss: 0.5315 - accuracy: 0.7420
Epoch 68/70
804/804 [==============================] - 4s 5ms/step - loss: 0.5314 - accuracy: 0.7425
Epoch 69/70
804/804 [==============================] - 3s 4ms/step - loss: 0.5313 - accuracy: 0.7411
Epoch 70/70
804/804 [==============================] - 3s 3ms/step - loss: 0.5307 - accuracy: 0.7402

#### Alternative Model 2

In [120]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [121]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = (number_input_features +1)//2

In [122]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = number_output_neurons_A2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

58

In [123]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2 = (hidden_nodes_layer1_A2 +1)//2

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A2

29

In [124]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [125]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation='relu'))

# Output layer
nn_A2.add(Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_23 (Dense)            (None, 58)                6786

 dense_24 (Dense)            (None, 1)                 59

=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

In [126]:
# Compile the model
nn_A2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [127]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.5852 - accuracy: 0.7172
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5570 - accuracy: 0.7286
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5528 - accuracy: 0.7308
Epoch 4/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5514 - accuracy: 0.7298
Epoch 5/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5503 - accuracy: 0.7318
Epoch 6/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5490 - accuracy: 0.7307
Epoch 7/100
804/804 [==============================] - 5s 7ms/step - loss: 0.5480 - accuracy: 0.7323
Epoch 8/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5471 - accuracy: 0.7318
Epoch 9/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5469 - accuracy: 0.7325
Epoch 10/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5460 - accuracy: 0.7326
Epoch 11/100
804/804 [==============================] - 5s 7ms/step - loss: 0.5459 - accuracy: 0.7331
Epoch 12/100
804/804 [==============================] - 4s 6ms/step - loss: 0.5453 - accuracy: 0.7328
Epoch 13/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5447 - accuracy: 0.7321
Epoch 14/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5440 - accuracy: 0.7336
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5440 - accuracy: 0.7330
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5438 - accuracy: 0.7346
Epoch 17/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5433 - accuracy: 0.7341
Epoch 18/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5435 - accuracy: 0.7338
Epoch 19/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5427 - accuracy: 0.7343
Epoch 20/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5429 - accuracy: 0.7325
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5424 - accuracy: 0.7355
Epoch 22/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5426 - accuracy: 0.7348
Epoch 23/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5420 - accuracy: 0.7353
Epoch 24/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5425 - accuracy: 0.7345
Epoch 25/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5414 - accuracy: 0.7348
Epoch 26/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5414 - accuracy: 0.7356
Epoch 27/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5414 - accuracy: 0.7357
Epoch 28/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5410 - accuracy: 0.7350
Epoch 29/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5407 - accuracy: 0.7365
Epoch 30/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5400 - accuracy: 0.7365
Epoch 31/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5409 - accuracy: 0.7347
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5399 - accuracy: 0.7355
Epoch 33/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5406 - accuracy: 0.7365
Epoch 34/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5397 - accuracy: 0.7362
Epoch 35/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5397 - accuracy: 0.7368
Epoch 36/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5401 - accuracy: 0.7355
Epoch 37/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5397 - accuracy: 0.7367
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5390 - accuracy: 0.7359
Epoch 39/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5393 - accuracy: 0.7368
Epoch 40/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5393 - accuracy: 0.7358
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5391 - accuracy: 0.7371
Epoch 42/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5394 - accuracy: 0.7367
Epoch 43/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5381 - accuracy: 0.7374
Epoch 44/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5389 - accuracy: 0.7367
Epoch 45/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5386 - accuracy: 0.7367
Epoch 46/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5382 - accuracy: 0.7374
Epoch 47/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5381 - accuracy: 0.7365
Epoch 48/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5377 - accuracy: 0.7379
Epoch 49/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5382 - accuracy: 0.7376
Epoch 50/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5376 - accuracy: 0.7381
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5388 - accuracy: 0.7380
Epoch 52/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5369 - accuracy: 0.7378
Epoch 53/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5375 - accuracy: 0.7378
Epoch 54/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5372 - accuracy: 0.7378
Epoch 55/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 56/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5375 - accuracy: 0.7377
Epoch 57/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5377 - accuracy: 0.7380
Epoch 58/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5367 - accuracy: 0.7366
Epoch 59/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5373 - accuracy: 0.7376
Epoch 60/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5370 - accuracy: 0.7366
Epoch 61/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5373 - accuracy: 0.7378
Epoch 62/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 63/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5369 - accuracy: 0.7373
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5366 - accuracy: 0.7385
Epoch 65/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7381
Epoch 66/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7366
Epoch 67/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7395
Epoch 68/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5359 - accuracy: 0.7384
Epoch 69/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7389
Epoch 70/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5358 - accuracy: 0.7383
Epoch 71/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5371 - accuracy: 0.7390
Epoch 72/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5359 - accuracy: 0.7383
Epoch 73/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7395
Epoch 74/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5357 - accuracy: 0.7398
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7390
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5359 - accuracy: 0.7385
Epoch 77/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5360 - accuracy: 0.7393
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5356 - accuracy: 0.7379
Epoch 79/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5354 - accuracy: 0.7395
Epoch 80/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5367 - accuracy: 0.7386
Epoch 81/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5354 - accuracy: 0.7402
Epoch 82/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.7402
Epoch 83/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7390
Epoch 84/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5352 - accuracy: 0.7398
Epoch 85/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7398
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5353 - accuracy: 0.7378
Epoch 87/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5349 - accuracy: 0.7392
Epoch 88/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7394
Epoch 89/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5345 - accuracy: 0.7393
Epoch 90/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5348 - accuracy: 0.7396
Epoch 91/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.7387
Epoch 92/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5350 - accuracy: 0.7382
Epoch 93/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5349 - accuracy: 0.7386
Epoch 94/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5349 - accuracy: 0.7389
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7393
Epoch 96/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7381
Epoch 97/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5350 - accuracy: 0.7388
Epoch 98/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5340 - accuracy: 0.7386
Epoch 99/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5345 - accuracy: 0.7392
Epoch 100/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5345 - accuracy: 0.7391

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [128]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 1s - loss: 0.5649 - accuracy: 0.7307 - 957ms/epoch - 4ms/step
Loss: 0.5649033784866333, Accuracy: 0.7307288646697998

In [136]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 0.5758 - accuracy: 0.7300 - 599ms/epoch - 2ms/step
Loss: 0.5758131146430969, Accuracy: 0.7300291657447815

In [132]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 1s - loss: 0.5712 - accuracy: 0.7299 - 1s/epoch - 5ms/step
Loss: 0.571246325969696, Accuracy: 0.729912519454956

### Step 3: Save each of your alternative models as an HDF5 file.

In [137]:
# Set the file path for the first alternative model
file_path = "AlphabetSoup_A1.h5"

# Export your model to a HDF5 file
nn_A1.save(file_path)

# Download the model to your computer
files.download(file_path)

In [138]:
# Set the file path for the second alternative model
file_path = "AlphabetSoup_A2.h5"

# Export your model to a HDF5 file
nn_A2.save(file_path)

# Download the model to your computer
files.download(file_path)